tasks:
  build:
    - gcloud builds submit --tag gcr.io/stackblitz/prio-$STACKBLITZ_PROJECT_SLUG
  deploy:
    - gcloud beta run deploy prio-$STACKBLITZ_PROJECT_SLUG --allow-unauthenticated --image gcr.io/stackblitz/prio-$STACKBLITZ_PROJECT_SLUG --region us-central1
  start:
    - sb run -t $STACKBLITZ_PROJECT_SOURCE
